#!/usr/bin/env python3
"""Regenerate the Android launcher assets from android/icon/ic_launcher.svg.

The SVG is the single source of truth. From it this script writes:

  * res/drawable/ic_launcher_foreground.xml and res/drawable/ic_launcher_monochrome.xml
    (VectorDrawables, consumed by the adaptive icon in mipmap-anydpi-v26)
  * res/mipmap-<density>/ic_launcher.png and ic_launcher_round.png, the bitmaps
    that minSdk 24 needs for API 24-25 and for launchers that ignore adaptive icons.

The generated files are committed, so this only runs when the art changes:

    cd app && python3 android/icon/generate_launcher_icons.py

Needs rsvg-convert (librsvg) on PATH. The output is checked by
test/android/launcher_icon_test.dart, which pins the PNG sizes, the resource
references and the safe zone.
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

ICON_DIR = Path(__file__).resolve().parent
RES = ICON_DIR.parent / "app" / "src" / "main" / "res"
MASTER = ICON_DIR / "ic_launcher.svg"
CANVAS = 108.0

#: density bucket -> launcher icon px
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}

ACCENT = "#A798D7"        # pi's violet, the same one the app draws with
BACKGROUND = "#12141A"    # pi's page background
MONOCHROME = "#FFFFFF"    # Android 13+ tints this itself
FOREGROUND_FILL = "#a798d7"


def path_data() -> str:
    match = re.search(r'<path[^>]*\sd="([^"]+)"', MASTER.read_text())
    if not match:
        sys.exit("no <path d=...> in " + str(MASTER))
    return match.group(1)


def vector_drawable(fill: str, path: str) -> str:
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by android/icon/generate_launcher_icons.py from ic_launcher.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="{fill}"
        android:pathData="{path}"/>
</vector>
'''


def composite_svg(path: str, round_icon: bool) -> str:
    # Legacy launchers draw the bitmap as-is, so the background is baked in
    # rather than left to the launcher's mask.
    clip = (
        '<clipPath id="c"><circle cx="54" cy="54" r="54"/></clipPath>'
        if round_icon
        else ""
    )
    group = ' clip-path="url(#c)"' if round_icon else ""
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="108" height="108" '
        f'viewBox="0 0 108 108"><defs>{clip}</defs>'
        f'<g{group}><rect width="108" height="108" fill="{BACKGROUND}"/>'
        f'<path d="{path}" fill="{ACCENT}"/></g></svg>'
    )


def rasterize(svg: str, px: int, out: Path) -> None:
    with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as tmp:
        tmp.write(svg)
        tmp_path = tmp.name
    subprocess.run(
        ["rsvg-convert", "-w", str(px), "-h", str(px), tmp_path, "-o", str(out)],
        check=True,
    )


def adaptive_icon(name: str) -> str:
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by android/icon/generate_launcher_icons.py. Android 8.0+ (API 26)
     masks this itself; the bitmaps beside it are the API 24-25 fallback. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>
</adaptive-icon>
'''


def main() -> None:
    path = path_data()

    (RES / "drawable" / "ic_launcher_foreground.xml").write_text(
        vector_drawable(FOREGROUND_FILL, path)
    )
    (RES / "drawable" / "ic_launcher_monochrome.xml").write_text(
        vector_drawable(MONOCHROME, path)
    )

    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(adaptive_icon("ic_launcher"))
    (anydpi / "ic_launcher_round.xml").write_text(adaptive_icon("ic_launcher_round"))

    for density, px in DENSITIES.items():
        out = RES / f"mipmap-{density}"
        out.mkdir(parents=True, exist_ok=True)
        rasterize(composite_svg(path, False), px, out / "ic_launcher.png")
        rasterize(composite_svg(path, True), px, out / "ic_launcher_round.png")
        print(f"{density}: {px}px")

    print("wrote shadow + monochrome vectors, adaptive XML and 10 bitmaps")


if __name__ == "__main__":
    main()
